# Add this section to your _config.yml
# You may ignore information you already have
# like title, url and such
#####################################

# Podcast Feed Settings

title:          Ben's "This Week In Medical School" Podcast
email:          broot@fastmail.com
description:    "I thought it would be fun to keep track of some of the highlights from each week of medical school. It took a lot of work to get into school my program, but now the fun starts. Thank you to my family, friends, and colleagues for all your love and support... and now: This week in Medical School!"
subtitle:       "Highlights in the training of a doctor"
url:            https://www.bencr.me/twims
lang:           en
author:         Benjamin Root
copyright:      "&#x2117; &amp; &#xA9; 2020"