# Add this section to your _config.yml
# You may ignore information you already have
# like title, url and such
#####################################

# Podcast Feed Settings

title:          Ben's Week In Medical School
email:          broot@fastmail.com
description:    "My journey through medical school, and amazing things about the human body and health."
subtitle:       "Highlights in my doctor training"
url:            https://www.bencr.me/twims
imageURL:	https://raw.githubusercontent.com/benroot/twims/gh-pages/images/cover1400.jpg
lang:           en
author:         Benjamin Root
copyright:      "&#x2117; &amp; &#xA9; 2020"